# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/huazhilun/untitled2/form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 635)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.Visual = QtWidgets.QPushButton(Form)
        self.Visual.setObjectName("Visual")
        self.horizontalLayout_15.addWidget(self.Visual)
        self.SSFMstep = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.SSFMstep.setFont(font)
        self.SSFMstep.setObjectName("SSFMstep")
        self.horizontalLayout_15.addWidget(self.SSFMstep)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.StepLengthEdit = QtWidgets.QLineEdit(Form)
        self.StepLengthEdit.setObjectName("StepLengthEdit")
        self.horizontalLayout_15.addWidget(self.StepLengthEdit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_16.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_16.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_16.addWidget(self.pushButton_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_17.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SignalSettingLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.SignalSettingLabel.setFont(font)
        self.SignalSettingLabel.setObjectName("SignalSettingLabel")
        self.verticalLayout_2.addWidget(self.SignalSettingLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ModulationFormatChose = QtWidgets.QComboBox(Form)
        self.ModulationFormatChose.setObjectName("ModulationFormatChose")
        self.ModulationFormatChose.addItem("")
        self.ModulationFormatChose.addItem("")
        self.ModulationFormatChose.addItem("")
        self.ModulationFormatChose.addItem("")
        self.verticalLayout.addWidget(self.ModulationFormatChose)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BaudRateLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.BaudRateLabel.setFont(font)
        self.BaudRateLabel.setObjectName("BaudRateLabel")
        self.horizontalLayout.addWidget(self.BaudRateLabel)
        self.BaudRateSpinBox = QtWidgets.QSpinBox(Form)
        self.BaudRateSpinBox.setObjectName("BaudRateSpinBox")
        self.horizontalLayout.addWidget(self.BaudRateSpinBox)
        self.BaudrateUnit = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.BaudrateUnit.setFont(font)
        self.BaudrateUnit.setObjectName("BaudrateUnit")
        self.horizontalLayout.addWidget(self.BaudrateUnit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ChannelNumberLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.ChannelNumberLabel.setFont(font)
        self.ChannelNumberLabel.setObjectName("ChannelNumberLabel")
        self.horizontalLayout_2.addWidget(self.ChannelNumberLabel)
        self.spinBoxChannelNumber = QtWidgets.QSpinBox(Form)
        self.spinBoxChannelNumber.setObjectName("spinBoxChannelNumber")
        self.horizontalLayout_2.addWidget(self.spinBoxChannelNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_14.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LaserSettingLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.LaserSettingLabel.setFont(font)
        self.LaserSettingLabel.setObjectName("LaserSettingLabel")
        self.verticalLayout_3.addWidget(self.LaserSettingLabel)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LinewidethLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.LinewidethLabel.setFont(font)
        self.LinewidethLabel.setObjectName("LinewidethLabel")
        self.horizontalLayout_3.addWidget(self.LinewidethLabel)
        self.LinewidthSpinBox = QtWidgets.QSpinBox(Form)
        self.LinewidthSpinBox.setObjectName("LinewidthSpinBox")
        self.horizontalLayout_3.addWidget(self.LinewidthSpinBox)
        self.LineWidthLabel2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.LineWidthLabel2.setFont(font)
        self.LineWidthLabel2.setObjectName("LineWidthLabel2")
        self.horizontalLayout_3.addWidget(self.LineWidthLabel2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LaserPowerLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.LaserPowerLabel.setFont(font)
        self.LaserPowerLabel.setObjectName("LaserPowerLabel")
        self.horizontalLayout_4.addWidget(self.LaserPowerLabel)
        self.LaserPowerSpinBox = QtWidgets.QSpinBox(Form)
        self.LaserPowerSpinBox.setObjectName("LaserPowerSpinBox")
        self.horizontalLayout_4.addWidget(self.LaserPowerSpinBox)
        self.LineWidthLabel2_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.LineWidthLabel2_2.setFont(font)
        self.LineWidthLabel2_2.setObjectName("LineWidthLabel2_2")
        self.horizontalLayout_4.addWidget(self.LineWidthLabel2_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SpanSettingLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.SpanSettingLabel.setFont(font)
        self.SpanSettingLabel.setObjectName("SpanSettingLabel")
        self.verticalLayout_7.addWidget(self.SpanSettingLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.SpanNumberLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.SpanNumberLabel.setFont(font)
        self.SpanNumberLabel.setObjectName("SpanNumberLabel")
        self.horizontalLayout_7.addWidget(self.SpanNumberLabel)
        self.SpanNumberSpinbox = QtWidgets.QSpinBox(Form)
        self.SpanNumberSpinbox.setObjectName("SpanNumberSpinbox")
        self.horizontalLayout_7.addWidget(self.SpanNumberSpinbox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SpanKind = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.SpanKind.setFont(font)
        self.SpanKind.setObjectName("SpanKind")
        self.horizontalLayout_8.addWidget(self.SpanKind)
        self.SpanKindChose = QtWidgets.QComboBox(Form)
        self.SpanKindChose.setObjectName("SpanKindChose")
        self.SpanKindChose.addItem("")
        self.SpanKindChose.addItem("")
        self.SpanKindChose.addItem("")
        self.horizontalLayout_8.addWidget(self.SpanKindChose)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.SpanLengthLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.SpanLengthLabel.setFont(font)
        self.SpanLengthLabel.setObjectName("SpanLengthLabel")
        self.horizontalLayout_9.addWidget(self.SpanLengthLabel)
        self.SpanlengthEdit = QtWidgets.QLineEdit(Form)
        self.SpanlengthEdit.setObjectName("SpanlengthEdit")
        self.horizontalLayout_9.addWidget(self.SpanlengthEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.EDFALabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.EDFALabel.setFont(font)
        self.EDFALabel.setObjectName("EDFALabel")
        self.verticalLayout_6.addWidget(self.EDFALabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.EDFAModelLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.EDFAModelLabel.setFont(font)
        self.EDFAModelLabel.setObjectName("EDFAModelLabel")
        self.horizontalLayout_5.addWidget(self.EDFAModelLabel)
        self.edfamode_combo = QtWidgets.QComboBox(Form)
        self.edfamode_combo.setObjectName("edfamode_combo")
        self.edfamode_combo.addItem("")
        self.edfamode_combo.addItem("")
        self.horizontalLayout_5.addWidget(self.edfamode_combo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.GainTargetPower = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.GainTargetPower.setFont(font)
        self.GainTargetPower.setObjectName("GainTargetPower")
        self.horizontalLayout_6.addWidget(self.GainTargetPower)
        self.edfavalue = QtWidgets.QLineEdit(Form)
        self.edfavalue.setObjectName("edfavalue")
        self.horizontalLayout_6.addWidget(self.edfavalue)
        self.SignalSetting_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.SignalSetting_13.setFont(font)
        self.SignalSetting_13.setObjectName("SignalSetting_13")
        self.horizontalLayout_6.addWidget(self.SignalSetting_13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.WSSLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.WSSLabel.setFont(font)
        self.WSSLabel.setObjectName("WSSLabel")
        self.verticalLayout_8.addWidget(self.WSSLabel)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.BwLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.BwLabel.setFont(font)
        self.BwLabel.setObjectName("BwLabel")
        self.horizontalLayout_10.addWidget(self.BwLabel)
        self.WSSbw = QtWidgets.QLineEdit(Form)
        self.WSSbw.setObjectName("WSSbw")
        self.horizontalLayout_10.addWidget(self.WSSbw)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.OpticalT = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.OpticalT.setFont(font)
        self.OpticalT.setObjectName("OpticalT")
        self.horizontalLayout_11.addWidget(self.OpticalT)
        self.WSSotf = QtWidgets.QLineEdit(Form)
        self.WSSotf.setObjectName("WSSotf")
        self.horizontalLayout_11.addWidget(self.WSSotf)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.WSSDistribution = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(21)
        self.WSSDistribution.setFont(font)
        self.WSSDistribution.setObjectName("WSSDistribution")
        self.horizontalLayout_12.addWidget(self.WSSDistribution)
        self.edfamode_combo_2 = QtWidgets.QComboBox(Form)
        self.edfamode_combo_2.setObjectName("edfamode_combo_2")
        self.edfamode_combo_2.addItem("")
        self.edfamode_combo_2.addItem("")
        self.horizontalLayout_12.addWidget(self.edfamode_combo_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.WSSdis = QtWidgets.QLineEdit(Form)
        self.WSSdis.setEnabled(True)
        self.WSSdis.setReadOnly(True)
        self.WSSdis.setObjectName("WSSdis")
        self.verticalLayout_8.addWidget(self.WSSdis)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Visual.setText(_translate("Form", "Visual"))
        self.SSFMstep.setText(_translate("Form", "step length"))
        self.pushButton.setText(_translate("Form", "Begin"))
        self.pushButton_2.setText(_translate("Form", "Stop"))
        self.pushButton_3.setText(_translate("Form", "SaveRes"))
        self.SignalSettingLabel.setText(_translate("Form", "Signal Setting "))
        self.ModulationFormatChose.setItemText(0, _translate("Form", "QPSK"))
        self.ModulationFormatChose.setItemText(1, _translate("Form", "16-QAM"))
        self.ModulationFormatChose.setItemText(2, _translate("Form", "32-QAM"))
        self.ModulationFormatChose.setItemText(3, _translate("Form", "64-QAM"))
        self.BaudRateLabel.setText(_translate("Form", "Baud Rate"))
        self.BaudrateUnit.setText(_translate("Form", "GHz"))
        self.ChannelNumberLabel.setText(_translate("Form", "nch"))
        self.LaserSettingLabel.setText(_translate("Form", "LaserSetting"))
        self.LinewidethLabel.setText(_translate("Form", "LW"))
        self.LineWidthLabel2.setText(_translate("Form", "GHz"))
        self.LaserPowerLabel.setText(_translate("Form", "power"))
        self.LineWidthLabel2_2.setText(_translate("Form", "dBm"))
        self.SpanSettingLabel.setText(_translate("Form", "Span Setting"))
        self.SpanNumberLabel.setText(_translate("Form", "Span Number"))
        self.SpanKind.setText(_translate("Form", "Span Kind"))
        self.SpanKindChose.setItemText(0, _translate("Form", "SSMF"))
        self.SpanKindChose.setItemText(1, _translate("Form", "ELEAF"))
        self.SpanKindChose.setItemText(2, _translate("Form", "TWC"))
        self.SpanLengthLabel.setText(_translate("Form", "Span length [km]"))
        self.EDFALabel.setText(_translate("Form", "EDFA"))
        self.EDFAModelLabel.setText(_translate("Form", "Mode"))
        self.edfamode_combo.setItemText(0, _translate("Form", "ConstantGain"))
        self.edfamode_combo.setItemText(1, _translate("Form", "ConstantPower"))
        self.GainTargetPower.setText(_translate("Form", "Value"))
        self.SignalSetting_13.setText(_translate("Form", "db/dbm"))
        self.WSSLabel.setText(_translate("Form", "WSS"))
        self.BwLabel.setText(_translate("Form", "BW[GHz]"))
        self.OpticalT.setText(_translate("Form", "OFT [GHz]"))
        self.WSSDistribution.setText(_translate("Form", "Distribution"))
        self.edfamode_combo_2.setItemText(0, _translate("Form", "EveryOne"))
        self.edfamode_combo_2.setItemText(1, _translate("Form", "UserDefine"))

